name: Upload logs

inputs:
  TEST_LABEL:
    required: true

runs:
  using: "composite"
  steps:
    - name: Save Hypergraph L0 - Genesis Node logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-hypergraph-dag-l0-genesis-node
        path: .github/code/hypergraph/dag-l0/genesis-node/*.log

    - name: Save Hypergraph L0 - Validator 1 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-hypergraph-dag-l0-validator-1
        path: .github/code/hypergraph/dag-l0/validator-1/*.log

    - name: Save Hypergraph L0 - Validator 2 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-hypergraph-dag-l0-validator-2
        path: .github/code/hypergraph/dag-l0/validator-2/*.log

    - name: Save Metagraph L0 - Genesis Node logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-l0-genesis-node
        path: .github/code/metagraphs/workchain/metagraph-l0/genesis-node/*.log

    - name: Save Metagraph L0 - Validator 1 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-l0-validator-1
        path: .github/code/metagraphs/workchain/metagraph-l0/validator-1/*.log

    - name: Save Metagraph L0 - Validator 2 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-l0-validator-2
        path: .github/code/metagraphs/workchain/metagraph-l0/validator-2/*.log

    - name: Save Data L1 - Initial Validator logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-data-l1-initial-validator
        path: .github/code/metagraphs/workchain/data-l1/initial-validator/*.log

    - name: Save Data L1 - Validator 1 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-data-l1-validator-1
        path: .github/code/metagraphs/workchain/data-l1/validator-1/*.log

    - name: Save Data L1 - Validator 2 logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.TEST_LABEL }}-metagraph-workchain-data-l1-validator-2
        path: .github/code/metagraphs/workchain/data-l1/validator-2/*.log
